<form action="login.pl" method="post">
<table cellspacing=0 border=1 align="center" class="maintable">
	<tr><td>Имя пользователя:</td><td><input type="text" name="username"></td></tr>
	<tr><td>Пароль:</td><td><input type="password" name="password"></td></tr>
	<tr><td><input type="submit" value="Войти"></td><td><input type="reset" value="Очистить"></td></tr>
	<input type="hidden" name="act" value="login">
</table>
</form>
